<?php
namespace app\index\controller;
use app\admin\model\Actioncategory;
use think\Request;

class Actions extends Actives
{
    private $actionscategory;
    private $cid;
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
        $this->actionscategory=Actioncategory::all();
        $this->cid=input('param.cid');
        if(!$this->cid){
            $this->cid=$this->actionscategory['0']['cid'];
        }
        $this->assign('actionscategory',$this->actionscategory);
        $this->assign('cid',$this->cid);
    }

    public function index(Request $request)
    {
        $list = \app\admin\model\Actions::where('cid',$this->cid)->order('create_time desc')->paginate(2);
        // 获取分页显示
        $page = $list->render();
        // 模板变量赋值
        $this->assign('list', $list);
        $this->assign('page', $page);
        return view();
    }

    public function content(Request $request){
        $data=\app\admin\model\Actions::get($request->param('nid'));
        $this->assign('data',$data);
        return view();
    }
}
