<?php
/**
 * Created by PhpStorm.
 * User : Leopard
 * Date : 2018/3/22
 * Time : 10:34
 * Email: 417780879@qq.com
 */
namespace app\index\controller;
use app\admin\model\Bottomnav;
use app\admin\model\Nav;
use think\Controller;

class Base extends Controller
{
    public $active=1;
    protected $model;
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
        $this->model=new Bottomnav();
        $oldnavData=$this->model->order('sort desc')->select()->toArray();
        $navData=[];
        $top=$this->model->where('pid',0)->order('sort desc')->select()->toArray();
        foreach($top as $k=>$v){
            $navData[$v['cid']]=$v;
        }
        foreach($oldnavData as $k=>$v){
            if($v['pid']>0){
                $navData[$v['pid']]['data'][]=$v;
            }
        }
        $topNavData=Nav::order('sort desc')->select()->toArray();
        $newCate=\app\admin\model\Category::order('sort desc')->select()->toArray();
        $actionsCate=\app\admin\model\Actioncategory::order('sort desc')->select()->toArray();
        $teamsCate=\app\admin\model\Teamcategory::order('sort desc')->select()->toArray();
        foreach($topNavData as $k=>$v){
            if($v['id']==2){
                $topNavData[$k]['data']=$newCate;
            }elseif($v['id']==3){
                $topNavData[$k]['data']=$actionsCate;
            }elseif($v['id']==4){
                $topNavData[$k]['data']=$teamsCate;
            }else{
                $topNavData[$k]['data']=['cid'=>0];
            }
        }
        $this->assign('topNavData',$topNavData);
        $this->assign('navData',$navData);
    }
}