<?php
namespace app\index\controller;
use app\admin\model\Introduction;
use app\index\model\Messages;
use think\Request;

class Contract extends Actives
{
    public function _initialize()
    {
        parent ::_initialize(); // TODO: Change the autogenerated stub
        $this->model=new Messages();
    }

    public function index(Request $request){
        $conData=current(Introduction::all()->toArray());
        $this->assign('conData',$conData);
        return view();
    }

    public function ajaxMessage(Request $request){
        if($request->isAjax()){
            $data=$request->param();
            $res=(new Messages())->storeWeb($data);
            return $res;
        }
    }
    public function test(Request $request){
        $data=$request->param();
        dump($data);
    }
}
